spring.application.name=voiceagent

spring.ai.openai.api-key=${OPENAI_API_KEY}
spring.ai.openai.chat.options.model=gpt-4.1-mini

spring.ai.openai.audio.transcription.model=gpt-4o-mini-transcribe

spring.ai.openai.audio.speech.model=gpt-4o-mini-tts
spring.ai.openai.audio.speech.voice=alloy
spring.ai.openai.audio.speech.response-format=mp3

logging.level.org.springframework.ai.chat.client.advisor=DEBUG

